CREATE PROCEDURE `copyTableBD` ()
LANGUAGE SQL
DETERMINISTIC
SQL SECURITY DEFINER
BEGIN
START TRANSACTION;
DROP TABLE IF EXISTS coin1;
CREATE TABLE IF NOT EXISTS coin1
SELECT * FROM coin1;
COMMIT;
END
